
jobs:
  build:
    docker:
    # specify the version you desire here
      - image: circleci/node:12.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # ... steps for building/testing app ...
      - setup_remote_docker
       # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run:
          name: Docker Build
          command: docker build -t devops-node-app .

      - run:
          name: Docker Test
          command: docker run devops-node-app npm test

      - run:
          name: Docker Run
          command: docker run -d -p 3000:3000 devops-node-app

      - run:
          name: Docker Deployment
          command: sh deployments/qa.sh

    branches:
      only: /main/